language: python
python:
    #  - "3.2" # scipy requires python >= 3.4
    #  - "3.3"
    #  - "3.4" # networkx2.0 requires python >= 3.6
  - "3.5"
  - "3.6"
env:
  - NETWORKX_VERSION=1.9
  - NETWORKX_VERSION=2.0

# Check pep8 formatting
# Copied from https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c
before_install:
- pip install pep8

# command to install dependencies
install:
  - pip install -q networkx==$NETWORKX_VERSION
  - pip install -q -r requirements.txt
# command to run tests
script:
# This runs test discovery on all modules with names ending '_test'
  - python3 -m pytest -v
# Copied from https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c
# Run pep8 on all .py files in all subfolders
# (I ignore "E402: module level import not at top of file"
# because of use case sys.path.append('..'); import <module>)
  - find . -name \*.py -exec pep8 --ignore=E402 {} +

# command to silence email notifications
notifications:
  email: false
